# Travis doesn't have a fortran build config, so we'll use c as a base and
# create our own environment
language: c
sudo: required

git:
    depth: 3
    quiet: true

env:
    matrix:
        - TYPE=ACCESS-CM
        - TYPE=ACCESS-OM
        - TYPE=MOM_solo
        - TYPE=MOM_SIS
        - TYPE=CM2M
        - TYPE=ESM2M
        - TYPE=ICCM
        - TYPE=EBM
    global:
        - FC=gfortran-4.8
        - OMPI_FC=${FC}
        - OASIS_ROOT=$TRAVIS_BUILD_DIR/Linux
    
matrix:
  allow_failures:
    - env: TYPE=ACCESS-OM
    # - env: TYPE=ACCESS-CM

install:
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install csh gcc-4.8 gfortran-4.8 libgomp1 openmpi-bin libopenmpi-dev  libnetcdf-dev  netcdf-bin

before_script:
    - curl -O $(curl -s https://api.github.com/repos/OceansAus/oasis3-mct/releases/latest | grep browser_download_url | cut -d: -f2- | tr -d ' "')
    - tar -xf binary_release.tar.gz

script: 
    - cd exp && ./MOM_compile.csh --type $TYPE --platform travis --use_netcdf4

# after_success:
#     - find .
#     - codecov --gcov-exec=gcov-4.8